### ISSUE TITLE
Parse error in parser.py for some domains

### ISSUE THREAD

**Issue by Nikita-Sp** [richardpenman/whois#126]
Hi, I'm new to python, but a web developer, so could handle that by commenting the string.
Maybe it's not a good solution, but fast.

So the issue is with the domain: medranosystems.com
The line from debug is: `raise PywhoisError(text)` on line 401 of parser.py I've got a parsing error:

> $ python test2.py
> Traceback (most recent call last):
>   File "D:\Python\test2.py", line 3, in <module>
>     w = whois.whois('medranosystems.com')
>   File "C:\*****\Python\Python310\lib\site-packages\whois\__init__.py", line 44, in whois
>     return WhoisEntry.load(domain, text)
>   File "C:\*****\Python\Python310\lib\site-packages\whois\parser.py", line 188, in load
>     return WhoisCom(domain, text)
>   File "C:\*****\Python\Python310\lib\site-packages\whois\parser.py", line 401, in __init__
>     raise PywhoisError(text)
> whois.parser.PywhoisError: No match for "MEDRANOSYSTEMS.COM".
> >>> Last update of whois database: 2022-05-27T16:06:02Z <<<
> 
> NOTICE: The expiration date displayed in this record is the date the
> registrar's sponsorship of the domain name registration in the registry is
> currently set to expire. This date does not necessarily reflect the expiration
> date of the domain name registrant's agreement with the sponsoring
> registrar.  Users may consult the sponsoring registrar's Whois database to
> view the registrar's reported date of expiration for this registration.
> 
> TERMS OF USE: You are not authorized to access or query our Whois
> database through the use of electronic processes that are high-volume and
> automated except as reasonably necessary to register domain names or
> modify existing registrations; the Data in VeriSign Global Registry
> Services' ("VeriSign") Whois database is provided by VeriSign for
> information purposes only, and to assist persons in obtaining information
> about or related to a domain name registration record. VeriSign does not
> guarantee its accuracy. By submitting a Whois query, you agree to abide
> by the following terms of use: You agree that you may use this Data only
> for lawful purposes and that under no circumstances will you use this Data
> to: (1) allow, enable, or otherwise support the transmission of mass
> unsolicited, commercial advertising or solicitations via e-mail, telephone,
> or facsimile; or (2) enable high volume, automated, electronic processes
> that apply to VeriSign (or its computer systems). The compilation,
> repackaging, dissemination or other use of this Data is expressly
> prohibited without the prior written consent of VeriSign. You agree not to
> use electronic processes that are automated and high-volume to access or
> query the Whois database except as reasonably necessary to register
> domain names or modify existing registrations. VeriSign reserves the right
> to restrict your access to the Whois database in its sole discretion to ensure
> operational stability.  VeriSign may restrict or terminate your access to the
> Whois database for failure to abide by these terms of use. VeriSign
> reserves the right to modify these terms at any time.
> 
> The Registry database contains ONLY .COM, .NET, .EDU domains and
> Registrars.

**Comment by Nikita-Sp** [comment]
UPD: solved with _try/except_ like:
`try:
    w = whois.whois('medranosystems.com')
except:
    w = 0`
