### ISSUE TITLE
Running on py3.10 causes import errors - "cannot import name 'Iterable' from 'collections'"

### ISSUE THREAD

**Issue by SimonGurney** [richardpenman/whois#137]
```
import whois
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\SimonGurney\AppData\Roaming\Python\Python310\site-packages\whois\__init__.py", line 15, in <module>
    from .parser import WhoisEntry
  File "C:\Users\SimonGurney\AppData\Roaming\Python\Python310\site-packages\whois\parser.py", line 18, in <module>
    from past.builtins import basestring
  File "C:\Users\SimonGurney\AppData\Roaming\Python\Python310\site-packages\past\builtins\__init__.py", line 43, in <module>
    from past.builtins.noniterators import (filter, map, range, reduce, zip)
  File "C:\Users\SimonGurney\AppData\Roaming\Python\Python310\site-packages\past\builtins\noniterators.py", line 24, in <module>
    from past.types import basestring
  File "C:\Users\SimonGurney\AppData\Roaming\Python\Python310\site-packages\past\types\__init__.py", line 25, in <module>
    from .oldstr import oldstr
  File "C:\Users\SimonGurney\AppData\Roaming\Python\Python310\site-packages\past\types\oldstr.py", line 5, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)
```

The fix at the moment is to manually add the references backs

```
import collections
collections.Iterable = collections.abc.Iterable
collections.Mapping = collections.abc.Mapping
import whois
```

**Comment by RedstonedLife** [comment]
Weird, I'm running this on Python `3.10.6` and I haven't received any such error

**Comment by richardpenman** [comment]
The `from past.builtins import basestring` line does not exist in the current codebase, so I will assume this is no longer an issue.
