### ISSUE TITLE
Problem with .ru zone

### ISSUE THREAD

**Issue by woodholly** [richardpenman/whois#207]
Stopped working for .ru domains, problem started 2 weeks ago, no problem with other zones.

**Comment by belykhk** [comment]
Can confirm that there is issue with some (not all) domains used with RU_HOST = "whois.nic.ru". After downgrading to version 0.8.0 issue is not reproducible.

python-whois==0.8.0:
```
>>> import whois
>>> whois.whois("whois.ru")
{'domain_name': 'WHOIS.RU', 'registrar': 'SALENAMES-RU', 'creation_date': datetime.datetime(1999, 5, 14, 13, 58, 12), 'expiration_date': datetime.datetime(2024, 5, 31, 21, 0), 'name_servers': ['jessica.ns.cloudflare.com.', 'trey.ns.cloudflare.com.'], 'status': 'REGISTERED, DELEGATED, VERIFIED', 'emails': None, 'org': 'Domain name registrar SALENAMES LTD.'}
```
python-whois=0.9.3:
```
>>> import whois
>>> whois.whois("whois.ru")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kgbelyh/.local/lib/python3.9/site-packages/whois/__init__.py", line 47, in whois
    entry = WhoisEntry.load(domain, text)
  File "/home/kgbelyh/.local/lib/python3.9/site-packages/whois/parser.py", line 202, in load
    return WhoisRu(domain, text)
  File "/home/kgbelyh/.local/lib/python3.9/site-packages/whois/parser.py", line 562, in __init__
    raise PywhoisError(text)
whois.parser.PywhoisError: No entries found for the selected source(s).

>>> Last update of WHOIS database: 2024.04.02T12:16:14Z <<<
```

**Comment by woodholly** [comment]
Yes, 0.8.0 works.

**Comment by richardpenman** [comment]
PR welcome to fix this!

**Comment by ELForcer** [comment]
Hello, The problem with python-whois version **0.9.4** is still present.
Here is an example of checking the site elforcer.ru on version **0.9.4**:
```
    R = whois.whois(domain_name)
  File "/home/elforcer/FlaskSite/MyProject/env/lib/python3.10/site-packages/whois/__init__.py", line 47, in whois
    entry = WhoisEntry.load(domain, text)
  File "/home/elforcer/FlaskSite/MyProject/env/lib/python3.10/site-packages/whois/parser.py", line 204, in load
    return WhoisRu(domain, text)
  File "/home/elforcer/FlaskSite/MyProject/env/lib/python3.10/site-packages/whois/parser.py", line 564, in __init__
    raise PywhoisError(text)
whois.parser.PywhoisError: No entries found for the selected source(s).

>>> Last update of WHOIS database: 2024.08.13T17:35:44Z <<<
```
Here is the answer for python-whois version **0.7.3**
```
{
  "domain_name": "ELFORCER.RU",
  "registrar": "REGRU-RU",
  "creation_date": "2021-01-23 20:40:22",
  "expiration_date": "2025-01-23 20:40:22",
  "name_servers": [
    "ns1.reg.ru.",
    "ns2.reg.ru."
  ],
  "status": "REGISTERED, DELEGATED, UNVERIFIED",
  "emails": null,
  "org": null
}
```
