### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by prono69** [richardpenman/whois#242]
Hello . I recently started using this library but getting this timeout issue everytime.

`
Traceback (most recent call last):
  File "/Ult/pyUltroid/_misc/_decorators.py", line 112, in wrapp
    await dec(ult)
  File "/Ult/addons/domaininfo.py", line 52, in get_domain_info
    domain_info = get_domain_hosting_info(domain_name)
  File "/Ult/addons/domaininfo.py", line 9, in get_domain_hosting_info
    domain_info = whois.whois(domain_name)
  File "/usr/local/lib/python3.9/site-packages/whois/__init__.py", line 46, in whois
    text = nic_client.whois_lookup(None, domain.encode("idna"), flags, quiet=quiet)
  File "/usr/local/lib/python3.9/site-packages/whois/whois.py", line 425, in whois_lookup
    nichost = self.choose_server(query_arg)
  File "/usr/local/lib/python3.9/site-packages/whois/whois.py", line 390, in choose_server
    return self.findwhois_iana(tld)
  File "/usr/local/lib/python3.9/site-packages/whois/whois.py", line 150, in findwhois_iana
    s.connect(("whois.iana.org", 43))
socket.timeout: timed out`

**Comment by richardpenman** [comment]
sounds like this is an issue with your IP being rate limited
