### ISSUE TITLE
Error for many TLDs

### ISSUE THREAD

**Issue by irfannaseefp** [richardpenman/whois#45]
I was doing a loop in all the TLDs listed in [IANA TLD list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) . It is failing for many TLDs with the following error.

```
>>> w = whois.whois("domainname.aarp")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/whois/__init__.py", line 43, in whois
    text = nic_client.whois_lookup(None, domain.encode('idna'), flags)
  File "/usr/local/lib/python3.8/dist-packages/whois/whois.py", line 264, in whois_lookup
    result = self.whois(query_arg, nichost, flags)
  File "/usr/local/lib/python3.8/dist-packages/whois/whois.py", line 142, in whois
    s.connect((hostname, 43))
socket.gaierror: [Errno -5] No address associated with hostname
```

**Comment by richardpenman** [comment]
That is expected behaviour for the example domain since "domainname.aarp" does not exist. Do you have an example for a domain that does exist?
